"""Build hook for immutable source-revision provenance.

The generated module is written only into setuptools' build directory.  It is
therefore present in ordinary wheels and non-editable installs without ever
creating or rewriting a file under ``src/``.
"""
from __future__ import annotations

import re
import subprocess
from pathlib import Path

from setuptools import setup
from setuptools.command.build_py import build_py


_SOURCE_ROOT = Path(__file__).resolve().parent
_FULL_GIT_SHA = re.compile(r"[0-9a-f]{40}\Z")


def _source_git_identity() -> tuple[str, bool]:
    """Return the checkout HEAD and repository-dirty state for this build."""
    try:
        revision = subprocess.run(
            ["git", "rev-parse", "--verify", "HEAD"],
            cwd=_SOURCE_ROOT,
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
        commit = revision.stdout.strip().lower()
        if revision.returncode != 0 or not _FULL_GIT_SHA.fullmatch(commit):
            return "unknown", False
        status = subprocess.run(
            ["git", "status", "--porcelain", "--untracked-files=normal"],
            cwd=_SOURCE_ROOT,
            capture_output=True,
            text=True,
            timeout=5,
            check=False,
        )
        # If the repository-state check itself fails, mark the otherwise known
        # revision dirty rather than presenting an unqualified clean build.
        dirty = status.returncode != 0 or bool(status.stdout.strip())
        return commit, dirty
    except (OSError, subprocess.SubprocessError):
        return "unknown", False


class BuildPyWithSourceRevision(build_py):
    """Add deterministic build provenance to the built package only."""

    def run(self) -> None:
        super().run()
        commit, dirty = _source_git_identity()
        destination = (
            Path(self.build_lib)
            / "symbolic_compactification"
            / "_build_info.py"
        )
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(
            "# Generated by setup.py; do not edit.\n"
            f"SOURCE_GIT_COMMIT = {commit!r}\n"
            f"SOURCE_GIT_DIRTY = {dirty!r}\n",
            encoding="utf-8",
        )


setup(cmdclass={"build_py": BuildPyWithSourceRevision})
