"""Shared Track-V interfaces. Subagents implement packages; do not edit this file."""
from __future__ import annotations

from typing import Any, Optional

STRATEGIES = (
    "DIRECT",
    "FACTOR_LOCAL",
    "SERIES_LOCAL",
    "DD_CERTIFICATE",
    "SPECIAL_FUNCTION_LOCAL",
    "UNKNOWN",
)

# Verdicts remain the engine constants. Timeout is UNKNOWN, never ZERO.
ZERO = "ZERO"
NONZERO = "NONZERO"
UNKNOWN = "UNKNOWN"
COMPILE_FAILURE = "COMPILE_FAILURE"

GAIN = ("V_GAIN", "C_GAIN", "NO_GAIN")


def route_name(name: str) -> str:
    n = (name or "UNKNOWN").upper()
    return n if n in STRATEGIES else "UNKNOWN"


def gain_label(*, old: Optional[str], new: Optional[str], compiled_before: bool) -> str:
    if old == new:
        return "NO_GAIN"
    if new in {ZERO, NONZERO} and not compiled_before:
        return "C_GAIN"
    if new in {ZERO, NONZERO} and old in {UNKNOWN, None, "UNSCORED", "V", "MIXED"}:
        return "V_GAIN"
    if new in {ZERO, NONZERO} and old == COMPILE_FAILURE:
        return "C_GAIN"
    return "NO_GAIN"
