"""RPS deterministic, symbolic, and auditable LLM search conditions."""

from .actions import (
    SEARCH_POLICY_VERSION,
    FrontierExpansion,
    SearchPolicy,
    apply_action,
    expand_state,
    initial_state,
    legal_actions,
)
from .candidates import (
    CANDIDATE_POLICY_VERSION,
    CandidatePool,
    LatentCandidate,
    extract_candidate_pool,
)
from .enumerative import enumerative_search
from .model import LegalAction, ObligationEvidence, SearchContractError, SearchState
from .public_case import PublicCase, PublicMember, load_public_case
from .random_control import random_search
from .results import ExpansionRecord, SearchResult
from .scoring import ComplexityBreakdown, complexity_breakdown, score_program
from .llm_contract import (
    LLM_ALLOWED_MODELS,
    LLM_BASE_URL,
    LLM_BATCH_SIZE,
    LLM_BEAM_WIDTH,
    LLM_PRIMARY_MODEL,
    LLM_RANKING_SCHEMA_VERSION,
    LLM_REASONING_EFFORT,
    LLM_RESPONSE_FORMAT,
    LLM_ROBUSTNESS_MODEL,
    LLM_SEARCH_PROTOCOL_VERSION,
    LLM_SEED_LABELS,
    LLM_THINKING_TYPE,
    ChatCompletionsTransport,
    DeepSeekSearchConfig,
    OpenAIChatCompletionsTransport,
    RankingResponse,
    TokenUsage,
    assert_llm_public_payload,
    atomic_write_json,
    build_ranking_request,
    call_and_validate_ranking,
    candidate_state_items,
    decision_record_hash,
    legal_action_items,
    public_case_payload,
    public_state_payload,
    request_hash,
)
from .llm_guided import (
    LLM_FALLBACK_POLICY,
    LLM_RUN_HEADER_VERSION,
    LLM_SEARCH_POLICY_VERSION,
    SYMBOLIC_COMPARISON_REQUIRES_MATCHED_BATCH_CONTROL,
    SYMBOLIC_COMPARISON_STATUS,
    LLMGuidedSearchResult,
    LLMSearchLayerRecord,
    llm_action_proposal_search,
    llm_guided_search,
    llm_state_ranking_search,
)
from .symbolic_beam import (
    SYMBOLIC_BEAM_POLICY_VERSION,
    SYMBOLIC_BEAM_WIDTH,
    BeamLayerRecord,
    PriorityRecord,
    SymbolicBeamResult,
    symbolic_beam_search,
)
from .symbolic_heuristic import (
    SYMBOLIC_HEURISTIC_VERSION,
    SYMBOLIC_HEURISTIC_WEIGHTS,
    SymbolicObservations,
    SymbolicPriority,
    extract_symbolic_observations,
    symbolic_priority,
    symbolic_priority_key,
)

__all__ = [
    "CANDIDATE_POLICY_VERSION",
    "SEARCH_POLICY_VERSION",
    "CandidatePool",
    "ComplexityBreakdown",
    "ExpansionRecord",
    "FrontierExpansion",
    "LatentCandidate",
    "LegalAction",
    "LLM_ALLOWED_MODELS",
    "LLM_BASE_URL",
    "LLM_BATCH_SIZE",
    "LLM_BEAM_WIDTH",
    "LLM_FALLBACK_POLICY",
    "LLM_RUN_HEADER_VERSION",
    "LLM_PRIMARY_MODEL",
    "LLM_RANKING_SCHEMA_VERSION",
    "LLM_REASONING_EFFORT",
    "LLM_RESPONSE_FORMAT",
    "LLM_ROBUSTNESS_MODEL",
    "LLM_SEARCH_POLICY_VERSION",
    "LLM_SEARCH_PROTOCOL_VERSION",
    "LLM_SEED_LABELS",
    "LLM_THINKING_TYPE",
    "SYMBOLIC_COMPARISON_REQUIRES_MATCHED_BATCH_CONTROL",
    "SYMBOLIC_COMPARISON_STATUS",
    "LLMGuidedSearchResult",
    "LLMSearchLayerRecord",
    "ObligationEvidence",
    "PublicCase",
    "PublicMember",
    "SearchContractError",
    "SearchPolicy",
    "SearchResult",
    "SearchState",
    "ChatCompletionsTransport",
    "DeepSeekSearchConfig",
    "OpenAIChatCompletionsTransport",
    "RankingResponse",
    "TokenUsage",
    "assert_llm_public_payload",
    "SYMBOLIC_BEAM_POLICY_VERSION",
    "SYMBOLIC_BEAM_WIDTH",
    "SYMBOLIC_HEURISTIC_VERSION",
    "SYMBOLIC_HEURISTIC_WEIGHTS",
    "BeamLayerRecord",
    "PriorityRecord",
    "SymbolicBeamResult",
    "SymbolicObservations",
    "SymbolicPriority",
    "apply_action",
    "atomic_write_json",
    "build_ranking_request",
    "call_and_validate_ranking",
    "candidate_state_items",
    "complexity_breakdown",
    "enumerative_search",
    "expand_state",
    "extract_candidate_pool",
    "extract_symbolic_observations",
    "initial_state",
    "decision_record_hash",
    "legal_action_items",
    "legal_actions",
    "llm_action_proposal_search",
    "llm_guided_search",
    "llm_state_ranking_search",
    "load_public_case",
    "random_search",
    "public_case_payload",
    "public_state_payload",
    "request_hash",
    "score_program",
    "symbolic_beam_search",
    "symbolic_priority",
    "symbolic_priority_key",
]
