#!/usr/bin/env python3
"""Frozen source-grounded derivation relations for Guo et al. arXiv:2511.16422v2.

Frozen BEFORE verification. Claim type is independent of engine outcome.
Printed equation numbers are the public identifiers.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EXPR = ROOT / "expressions"


def load(name: str) -> str:
    return (EXPR / name).read_text().strip()


def R(
    display: str,
    cue: str,
    move: str,
    claimed: str,
    prose: str,
    sources: list[str],
    targets: list[str],
    *,
    executable: bool = False,
    left: str | None = None,
    right: str | None = None,
    subst: dict | None = None,
    condition: str = "none",
    parent_status: str | None = None,
    regression: str | None = None,
    helper: bool = False,
    tex_lines: list | None = None,
) -> dict:
    return {
        "display": display,
        "cue": cue,
        "move": move,
        "claimed": claimed,
        "prose": prose,
        "sources": sources,
        "targets": targets,
        "executable": executable,
        "left": left,
        "right": right,
        "subst": subst,
        "condition": condition,
        "parent_status": parent_status,
        "regression": regression,
        "helper": helper,
        "tex_lines": tex_lines or [],
    }


# ---------------------------------------------------------------------------
# Relations. Order follows the paper. Do not invent adjacency equalities.
# ---------------------------------------------------------------------------
RELATIONS: list[dict] = [
    # ----- main text -----
    R(
        "Eq. (1)",
        r"$\Gamma$ expansion of $\sigma_{abc}$",
        "asymptotic expansion",
        "ASYMPTOTIC_CLAIM",
        "this microscopic derivation yields ... expansion of the resulting conductivity by powers of $1/\\Gamma$",
        ["1"],
        ["1"],
        parent_status="UNKNOWN_REMAINDER",
        condition=r"author-declared $O(\Gamma)$ remainder",
        tex_lines=[169, 174],
    ),
    R(
        "Eq. (4)",
        r"$\sigma^{(0)}=\sigma^{\mathrm{kin}}+\sigma^{\mathrm{geo}}$",
        "definition",
        "SPLIT_PARENT",
        "the open-system formalism reveals a decomposition into distinct kinetic and geometric components",
        ["4"],
        ["4"],
        tex_lines=[191, 193],
    ),
    R(
        "Eq. (7) -> Eq. (8)",
        r"block-diagonal $S=\tau_z\sigma_z$ form",
        "definition",
        "DEFINITION_INSERTION",
        "this allows for a unitary transformation that separates $\\mathcal{H}(\\mathbf{k})$ into the $S=\\pm 1$ eigenspaces, yielding the block-diagonal form",
        ["7"],
        ["8"],
        tex_lines=[247, 256],
    ),
    R(
        "Eq. (D-57) -> Eq. (1)",
        r"main-text $\Gamma$ expansion",
        "bookkeeping",
        "BOOKKEEPING",
        "Appendix D repeats the same $\\Gamma$ expansion that the main text reports as Eq. (1)",
        ["D-57"],
        ["1"],
        parent_status="UNKNOWN_REMAINDER",
        condition=r"author-declared $O(\Gamma)$ remainder",
        tex_lines=[732, 736],
    ),
    R(
        "Eq. (D-69) -> Eq. (2)",
        r"$\sigma^{(-2)}$ with $f_n'=2f_{0,n}'$",
        "substitution",
        "INDEX_RELABELING",
        r"Eq. (D-69) writes $f_n'=2f_{0,n}'$ and the main text reports the $f_0$ form as Eq. (2)",
        ["D-69"],
        ["2"],
        executable=True,
        left="-Rational(1,8)*da_vbc*fnp",
        right="-Rational(1,4)*da_vbc*f0np",
        subst={"fnp": "2*f0np"},
        condition=r"substitute $f_n'=2f_{0,n}'$",
        tex_lines=[847, 852],
    ),
    R(
        "Eq. (D-78) -> Eq. (3)",
        r"$\sigma^{(-1)}$ with $f_n'=2f_{0,n}'$",
        "substitution",
        "INDEX_RELABELING",
        r"Eq. (D-78) writes $f_n'=2f_{0,n}'$ and the main text reports the $f_0$ form as Eq. (3)",
        ["D-78"],
        ["3"],
        executable=True,
        left="Rational(1,4)*kernel*fnp",
        right="Rational(1,2)*kernel*f0np",
        subst={"fnp": "2*f0np"},
        condition=r"substitute $f_n'=2f_{0,n}'$",
        tex_lines=[924, 929],
    ),
    R(
        "Eq. (D-117) -> Eq. (5)",
        r"$\sigma^{\mathrm{kin}}$ with $f_n^{(4)}=2f_{0,n}^{(4)}$",
        "substitution",
        "INDEX_RELABELING",
        r"Eq. (D-117) writes $f_n'=2f_{0,n}'$ on the kinetic term; main-text Eq. (5) is the $f_0$ form",
        ["D-117"],
        ["5"],
        executable=True,
        left="Rational(1,48)*va*vb*vc*f4",
        right="Rational(1,24)*va*vb*vc*f04",
        subst={"f4": "2*f04"},
        condition=r"substitute $f_n^{(4)}=2f_{0,n}^{(4)}$",
        tex_lines=[1226, 1232],
    ),
    R(
        "Eq. (D-127) -> Eq. (6)",
        r"$\sigma^{\mathrm{geo}}$ compact form",
        "bookkeeping",
        "BOOKKEEPING",
        "main-text Eq. (6) is the multiband/$f_0$ presentation of the two-band compact geometric result Eq. (D-127)",
        ["D-127"],
        ["6"],
        tex_lines=[1297, 1305],
    ),
    # ----- Appendix A -----
    R(
        "Eq. (A-10)",
        r"$\rho_S=\rho^{(0)}+\rho^{(1)}+\rho^{(2)}+O(V^3)$",
        "asymptotic expansion",
        "ASYMPTOTIC_CLAIM",
        r"we solve for the NESS density matrix by expanding $\rho_S(t)$ perturbatively in the driving perturbation $V(t)$",
        ["A-10"],
        ["A-10"],
        parent_status="UNKNOWN_REMAINDER",
        condition=r"author-declared $O(V^3)$ remainder",
        tex_lines=[349, 352],
    ),
    R(
        "Eq. (A-11) -> Eq. (A-14)",
        r"bath integral $\to$ polygamma $f_\pm$",
        "special function identity",
        "SPECIAL_FUNCTION_IDENTITY",
        r"the integrals over the bath variable $\omega_b$ in Eqs. (A-11) to (A-13) can be performed using the Cauchy residue theorem",
        ["A-11"],
        ["A-14"],
        tex_lines=[389, 404],
    ),
    R(
        "Eq. (A-14) -> Eq. (A-15)",
        r"$\Gamma\to 0$ recovers $f_0$",
        "limit",
        "LIMIT_CLAIM",
        r"which shows that $\tilde\rho_n^{(0)}$ reduces to the ideal Fermi-Dirac distribution in the limit of $\Gamma\to 0$",
        ["A-14"],
        ["A-15"],
        tex_lines=[406, 409],
    ),
    R(
        "Eq. (A-12) -> Eq. (A-16)",
        r"$\tilde\rho^{(1)}$ residue form",
        "special function identity",
        "SPECIAL_FUNCTION_IDENTITY",
        r"moreover, for the first- and second-order expansions, we have",
        ["A-12"],
        ["A-16"],
        tex_lines=[411, 420],
    ),
    R(
        "Eq. (A-17) -> Eq. (A-16)",
        r"$r_\pm^{(1)}$ inserted in $\tilde\rho^{(1)}$",
        "definition",
        "DEFINITION_INSERTION",
        "with (the $r_\\pm^{(1)}$ kernels)",
        ["A-17"],
        ["A-16"],
        tex_lines=[421, 428],
    ),
    R(
        "Eq. (A-13) -> Eq. (A-18)",
        r"$\tilde\rho^{(2)}$ residue form",
        "special function identity",
        "SPECIAL_FUNCTION_IDENTITY",
        "and (the second-order kernel in polygamma form)",
        ["A-13"],
        ["A-18"],
        tex_lines=[429, 442],
    ),
    R(
        "Eqs. (A-19), (A-20) -> Eq. (A-18)",
        r"$r_\pm^{(2)}$ inserted in $\tilde\rho^{(2)}$",
        "definition",
        "DEFINITION_INSERTION",
        "in which (the $r_\\pm^{(2)}$ kernels)",
        ["A-19", "A-20"],
        ["A-18"],
        tex_lines=[443, 457],
    ),
    # ----- Appendix B -----
    R(
        "Eq. (B-23) -> Eq. (B-24)",
        r"$j_a^{(2)}$ split into (I)--(IV)",
        "bookkeeping",
        "SPLIT_PARENT",
        "this leads to four distinct contributions to the second-order current",
        ["B-23"],
        ["B-24"],
        regression="B.split-j2",
        tex_lines=[478, 489],
    ),
    R(
        "Eq. (B-24) -> Eq. (B-25)",
        r"four channels $\to$ $\sigma_{abc}(\omega_1,\omega_2)$",
        "bookkeeping",
        "BOOKKEEPING",
        r"translating terms (I)--(IV) into the full frequency-dependent conductivity, we obtain",
        ["B-24"],
        ["B-25"],
        regression="B.j2-to-sigma",
        tex_lines=[490, 511],
    ),
    R(
        "Eq. (B-25) -> Eq. (B-26)",
        r"DC limit $\omega_1\to 0$, $\omega_2\to-\omega_1$",
        "limit",
        "LIMIT_CLAIM",
        r"the DC conductivity is obtained by taking two sequential limits of Eq. (B-25)",
        ["B-25"],
        ["B-26"],
        tex_lines=[513, 518],
    ),
    # ----- Appendix C (series / remainder; no invented adjacency) -----
    R(
        "Eq. (C-27)",
        r"Taylor kernels $\mathcal{C}^{(1,k)}$, $\mathcal{C}^{(2,k)}$",
        "definition",
        "SERIES_COEFFICIENT",
        r"we define the expansion coefficients via Taylor expansion around $\omega=0$",
        ["C-27"],
        ["C-27"],
        tex_lines=[527, 531],
    ),
    R(
        "Eq. (C-29) -> Eq. (C-30)",
        r"intraband $\mathcal{C}_{nn}^{(1,2)}$ in $\Gamma$",
        "asymptotic expansion",
        "ASYMPTOTIC_CLAIM",
        r"its Taylor expansion in $\Gamma$ is",
        ["C-29", "C-28"],
        ["C-30"],
        parent_status="UNKNOWN_REMAINDER",
        condition=r"author-declared $O(\Gamma)$ remainder",
        tex_lines=[544, 552],
    ),
    R(
        "Eq. (C-31) -> Eq. (C-32)",
        r"interband $\mathcal{C}_{nm}^{(1,2)}$ in $\Gamma$",
        "asymptotic expansion",
        "ASYMPTOTIC_CLAIM",
        r"its Taylor expansion in $\Gamma$ is",
        ["C-31", "C-28"],
        ["C-32"],
        parent_status="UNKNOWN_REMAINDER",
        condition=r"author-declared $O(\Gamma)$ remainder",
        tex_lines=[556, 566],
    ),
    R(
        "Eq. (C-33) -> Eq. (C-34)",
        r"$\mathcal{C}_{nnn}^{(2,2)}$ in $\Gamma$",
        "asymptotic expansion",
        "ASYMPTOTIC_CLAIM",
        r"its Taylor expansion in $\Gamma$ is",
        ["C-33", "C-28"],
        ["C-34"],
        parent_status="UNKNOWN_REMAINDER",
        condition=r"author-declared $O(\Gamma)$ remainder",
        tex_lines=[572, 578],
    ),
    R(
        "Eqs. (C-36), (C-37), (C-38) -> Eq. (C-35)",
        r"$\mathcal{C}_{nmn}^{(2,2)}=P_0+P_1+P_2$",
        "bookkeeping",
        "BOOKKEEPING",
        r"the expression for $\mathcal{C}_{nmn}^{(2,2)}$ is composed of terms involving $\psi^{(0)}$, $\psi^{(1)}$, and $\psi^{(2)}$",
        ["C-36", "C-37", "C-38"],
        ["C-35"],
        tex_lines=[581, 606],
    ),
    R(
        "Eq. (C-35) -> Eq. (C-39)",
        r"mixed $\mathcal{C}_{nmn}^{(2,2)}$ in $\Gamma$",
        "asymptotic expansion",
        "ASYMPTOTIC_CLAIM",
        r"its Taylor expansion in $\Gamma$ is",
        ["C-35", "C-28"],
        ["C-39"],
        parent_status="UNKNOWN_REMAINDER",
        condition=r"author-declared $O(\Gamma)$ remainder",
        tex_lines=[583, 611],
    ),
    R(
        "Eqs. (C-41)--(C-44) -> Eq. (C-40)",
        r"$\mathcal{C}_{nnm}^{(2,2)}\propto Q_0+Q_1+Q_2+Q_3$",
        "definition",
        "DEFINITION_INSERTION",
        r"where the terms $Q_n$ correspond to contributions involving $\psi^{(n)}$",
        ["C-41", "C-42", "C-43", "C-44"],
        ["C-40"],
        tex_lines=[613, 641],
    ),
    R(
        "Eq. (C-40) -> Eq. (C-45)",
        r"$\mathcal{C}_{nnm}^{(2,2)}$ Laurent in $\Gamma$",
        "asymptotic expansion",
        "ASYMPTOTIC_CLAIM",
        r"its Taylor expansion in $\Gamma$ is",
        ["C-40", "C-28"],
        ["C-45"],
        parent_status="UNKNOWN_REMAINDER",
        condition=r"author-declared $O(\Gamma)$ remainder",
        tex_lines=[615, 647],
    ),
    R(
        "Eqs. (C-47)--(C-50) -> Eq. (C-46)",
        r"$\mathcal{C}_{nmm}^{(2,2)}\propto U_0+\cdots+U_3$",
        "definition",
        "DEFINITION_INSERTION",
        "similarly, the expression for $\\mathcal{C}_{nmm}^{(2,2)}$ is given by",
        ["C-47", "C-48", "C-49", "C-50"],
        ["C-46"],
        tex_lines=[649, 677],
    ),
    R(
        "Eq. (C-46) -> Eq. (C-51)",
        r"$\mathcal{C}_{nmm}^{(2,2)}$ Laurent in $\Gamma$",
        "asymptotic expansion",
        "ASYMPTOTIC_CLAIM",
        r"its Taylor expansion in $\Gamma$ is",
        ["C-46", "C-28"],
        ["C-51"],
        parent_status="UNKNOWN_REMAINDER",
        condition=r"author-declared $O(\Gamma)$ remainder",
        tex_lines=[651, 683],
    ),
    R(
        "Eqs. (C-53), (C-54), (C-55) -> Eq. (C-52)",
        r"$\mathcal{C}_{nml}^{(2,2)}\propto R_0+R_1+R_2$",
        "definition",
        "DEFINITION_INSERTION",
        r"the fully interband coefficient ... comprises contributions from $\psi^{(0)}$, $\psi^{(1)}$, and $\psi^{(2)}$",
        ["C-53", "C-54", "C-55"],
        ["C-52"],
        tex_lines=[687, 714],
    ),
    R(
        "Eq. (C-52) -> Eq. (C-56)",
        r"fully interband $\mathcal{C}_{nml}^{(2,2)}$ in $\Gamma$",
        "asymptotic expansion",
        "ASYMPTOTIC_CLAIM",
        r"the Taylor expansion of the coefficient with respect to $\Gamma$ is given by",
        ["C-52", "C-28"],
        ["C-56"],
        parent_status="UNKNOWN_REMAINDER",
        condition=r"author-declared $O(\Gamma)$ remainder",
        tex_lines=[689, 723],
    ),
]

# Appendix D is appended below in extend_d().
# Appendix E/F/G similarly.


def extend_d() -> list[dict]:
    return [
        R(
            "Eq. (D-57)",
            r"$\sigma_{abc}=\Gamma^{-2}\sigma^{(-2)}+\Gamma^{-1}\sigma^{(-1)}+\sigma^{(0)}+O(\Gamma)$",
            "asymptotic expansion",
            "ASYMPTOTIC_CLAIM",
            r"we perform a Taylor expansion of the full DC conductivity $\sigma_{abc}$ in the relaxation rate $\Gamma$ around $\Gamma=0$",
            ["D-57"],
            ["D-57"],
            parent_status="UNKNOWN_REMAINDER",
            condition=r"author-declared $O(\Gamma)$ remainder",
            regression="D.gamma-asymptotic",
            tex_lines=[732, 737],
        ),
        R(
            "Eq. (D-59) -> Eq. (D-60)",
            r"$K_{1A}$ regroup",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"we reorganize $K_{1A}$ and apply the Metric-Velocity Relation",
            ["D-59"],
            ["D-60"],
            executable=True,
            left=load("K1A_expanded.txt"),
            right=load("K1A_regrouped.txt"),
            regression="D.K1A-regroup",
            tex_lines=[782, 788],
        ),
        R(
            "Key Identities -> Eq. (D-60)",
            r"metric-velocity pair index order",
            "algebra",
            "PAIRWISE_REDUCTION",
            r"metric-velocity relation $v_{12}^a v_{21}^b+v_{12}^b v_{21}^a=2\epsilon_{12}^2 g_{ab}$",
            [],
            ["D-60"],
            executable=True,
            left=load("mv_pair_paper_order.txt"),
            right=load("mv_pair_K1A_order.txt"),
            regression="D.metric-pair",
            tex_lines=[757, 759],
        ),
        R(
            "Eq. (D-60)",
            r"$K_{1A}\to 2\epsilon_{12}^2(v_1^c g_{ab}+v_1^b g_{ac})$",
            "substitution",
            "ALGEBRAIC_EQUIVALENCE",
            r"we reorganize $K_{1A}$ and apply the Metric-Velocity Relation",
            ["D-60"],
            ["D-60"],
            executable=True,
            left=load("K1A_regrouped.txt"),
            right=load("K1A_metric.txt"),
            subst={
                "v21a*v12b + v12a*v21b": "2*e12**2*gab",
                "v21a*v12c + v12a*v21c": "2*e12**2*gac",
            },
            condition=r"substitute $v_{12}^a v_{21}^b+v_{12}^b v_{21}^a=2\epsilon_{12}^2 g_{ab}$",
            regression="D.K1A-metric-subst",
            tex_lines=[784, 788],
        ),
        R(
            "Eq. (D-60) -> Eq. (D-61)",
            r"$T_A^{(-2)}$ prefactor $2\epsilon_{12}^2/(8\epsilon_{12})=\epsilon_{12}/4$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"the contribution to $\sigma_{abc}^{(-2)}$ from these terms is $T_A^{(-2)}$",
            ["D-60"],
            ["D-61"],
            executable=True,
            left=load("TA_unreduced.txt"),
            right=load("TA_reduced.txt"),
            regression="D.TA-prefactor",
            tex_lines=[790, 796],
        ),
        R(
            "Eq. (D-62)",
            r"$T_B^{(-2)}$ prefactor from $K_{nB}$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"the contribution to $\sigma_{abc}^{(-2)}$ from the $K_B$ terms is $T_B^{(-2)}$",
            ["D-62"],
            ["D-62"],
            executable=True,
            left="(1/(8*e12))*(-((v11ac*v1b + v11ab*v1c)*e12)*f1p + (-(v22ac*v2b + v22ab*v2c)*e12)*f2p)",
            right="(e12/(8*e12))*(-(v11ac*v1b + v11ab*v1c)*f1p - (v22ac*v2b + v22ab*v2c)*f2p)",
            tex_lines=[800, 805],
        ),
        R(
            "Eq. (D-62) -> Eq. (D-63)",
            r"insert $v_{nn}^{ab}=\partial_a\partial_b\epsilon_n-2\epsilon_{n\bar n}g_{ab}$",
            "definition",
            "DEFINITION_INSERTION",
            r"we use the identity for the diagonal second derivative",
            ["D-62"],
            ["D-63"],
            tex_lines=[806, 811],
        ),
        R(
            "Eq. (D-63) -> Eq. (D-64)",
            r"$T_B=T_{B,\mathrm{intra}}+T_{B,\mathrm{geo}}$",
            "definition",
            "SPLIT_PARENT",
            r"we separate this into an intraband part and a geometric part",
            ["D-63"],
            ["D-64"],
            tex_lines=[812, 817],
        ),
        R(
            "Eq. (D-64) -> Eq. (D-65)",
            r"$T_{B,\mathrm{intra}}=-\frac18\sum_n\partial_a(v_n^b v_n^c)f_n'$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"$T_{B,\mathrm{intra}}^{(-2)}=\cdots=-\frac18\sum_n\partial_a(v_n^b v_n^c)f_n'$",
            ["D-64"],
            ["D-65"],
            tex_lines=[819, 823],
        ),
        R(
            "Eq. (D-64) -> Eq. (D-66)",
            r"$T_{B,\mathrm{geo}}$ two-band form",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"and (the geometric $K_B$ piece)",
            ["D-64"],
            ["D-66"],
            executable=True,
            left="(-Rational(1,8))*(-2)*e12*(gac*v1b + gab*v1c)*f1p + (-Rational(1,8))*(-2)*e21*(gac*v2b + gab*v2c)*f2p",
            right="Rational(1,4)*(e12*(gac*v1b + gab*v1c)*f1p + e21*(gac*v2b + gab*v2c)*f2p)",
            tex_lines=[825, 829],
        ),
        R(
            "Eq. (D-66) -> Eq. (D-67)",
            r"$T_{B,\mathrm{geo}}$ with $\epsilon_{21}=-\epsilon_{12}$",
            "substitution",
            "ALGEBRAIC_EQUIVALENCE",
            r"using $\epsilon_{21}=-\epsilon_{12}$",
            ["D-66"],
            ["D-67"],
            executable=True,
            left=load("TBgeo_e21.txt"),
            right=load("TBgeo_e12.txt"),
            subst={"e21": "-e12"},
            condition=r"substitute $\epsilon_{21}=-\epsilon_{12}$",
            regression="D.TBgeo-eps21",
            tex_lines=[830, 836],
        ),
        R(
            "Eqs. (D-61), (D-67) -> Eq. (D-68)",
            r"$T_A+T_{B,\mathrm{geo}}$ cancellation",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"comparing the geometric terms $T_A^{(-2)}$ and $T_{B,\mathrm{geo}}^{(-2)}$, we find they are exactly opposite",
            ["D-61", "D-67"],
            ["D-68"],
            executable=True,
            left=load("TA_plus_TBgeo.txt"),
            right=load("zero.txt"),
            regression="D.TA-TBgeo-cancel",
            tex_lines=[837, 845],
        ),
        R(
            "Eqs. (D-65), (D-68) -> Eq. (D-69)",
            r"$\sigma^{(-2)}$ purely intraband",
            "substitution",
            "INDEX_RELABELING",
            r"the total conductivity $\sigma_{abc}^{(-2)}$ is therefore purely intraband; $f_n'=2f_{0,n}'$",
            ["D-65", "D-68"],
            ["D-69"],
            condition=r"after $T_A+T_{B,\mathrm{geo}}=0$; convention $f_n'=2f_{0,n}'$",
            tex_lines=[846, 852],
        ),
        R(
            "Eq. (D-71) -> Eq. (D-72)",
            r"$C_1,C_2$ regroup",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"we reorganize these expressions by factoring out the intraband velocities",
            ["D-71"],
            ["D-72"],
            executable=True,
            left=load("C12_expanded.txt"),
            right=load("C12_regrouped.txt"),
            regression="D.C12-regroup",
            tex_lines=[873, 880],
        ),
        R(
            "Eq. (D-73)",
            r"$V_{ab}$ Feynman--Hellmann expansion",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"we utilize the Feynman-Hellmann identity ($v_{nm}^a=-i\epsilon_{mn}A_{nm}^a$)",
            ["D-73"],
            ["D-73"],
            executable=True,
            left=load("Vab_FH.txt"),
            right=load("Vab_factored.txt"),
            regression="D.Vab-expand",
            tex_lines=[882, 891],
        ),
        R(
            "Eq. (D-73) (second equality)",
            r"$V_{ab}$ with $\epsilon_{12}\epsilon_{21}=-\epsilon_{12}^2$",
            "substitution",
            "ALGEBRAIC_EQUIVALENCE",
            r"$(\epsilon_{12}\epsilon_{21}=-\epsilon_{12}^2)$",
            ["D-73"],
            ["D-73"],
            executable=True,
            left=load("Vab_factored.txt"),
            right=load("Vab_e12sq.txt"),
            subst={"e21": "-e12"},
            condition=r"substitute $\epsilon_{21}=-\epsilon_{12}$",
            regression="D.Vab-eps21",
            tex_lines=[882, 891],
        ),
        R(
            "Eq. (D-74)",
            r"$A_{21}^a A_{12}^b-A_{12}^a A_{21}^b=-(A_{12}^a A_{21}^b-A_{12}^b A_{21}^a)$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"we relate the term in $V_{ab}$ to $\Omega_{ab}^1$",
            ["D-74"],
            ["D-74"],
            executable=True,
            left=load("A_pair.txt"),
            right=load("A_pair_swapped.txt"),
            regression="D.A-antisym",
            tex_lines=[896, 900],
        ),
        R(
            "Eq. (D-74) -> Eq. (D-75)",
            r"$V_{ab}=i\epsilon_{12}^2\Omega_{ab}^1$",
            "substitution",
            "ALGEBRAIC_EQUIVALENCE",
            r"substituting this back into $V_{ab}$",
            ["D-74"],
            ["D-75"],
            executable=True,
            left=load("A_pair_swapped.txt"),
            right=load("i_Omega.txt"),
            subst={"Oab1": "I*(A12a*A21b - A12b*A21a)"},
            condition=r"substitute $\Omega_{ab}^1:=i(A_{12}^a A_{21}^b-A_{12}^b A_{21}^a)$",
            regression="D.A-to-Omega",
            tex_lines=[901, 906],
        ),
        R(
            "Eqs. (D-72), (D-75) -> Eq. (D-76)",
            r"$C_1,C_2$ in $\Omega$",
            "substitution",
            "ALGEBRAIC_EQUIVALENCE",
            r"we substitute the expression for $V_{ab}$ back into the coefficients $C_1$ and $C_2$",
            ["D-72", "D-75"],
            ["D-76"],
            executable=True,
            left="v1c*(I*e12**2*Oab1) + v1b*(I*e12**2*Oac1)",
            right="I*e12**2*(v1c*Oab1 + v1b*Oac1)",
            tex_lines=[908, 915],
        ),
        R(
            "Eqs. (D-70), (D-76) -> Eq. (D-77)",
            r"$(-i)(i\epsilon_{12}^2)/(4\epsilon_{12}^2)=1/4$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"finally, we substitute $C_1$ and $C_2$ into the expression for $\sigma_{abc}^{(-1)}$",
            ["D-70", "D-76"],
            ["D-77"],
            executable=True,
            left=load("sigma_m1_with_i.txt"),
            right=load("sigma_m1_simplified.txt"),
            regression="D.sigma-m1-Ii",
            tex_lines=[916, 922],
        ),
        R(
            "Eq. (D-77) -> Eq. (D-78)",
            r"$\Omega^2=-\Omega^1$ compactification",
            "index relabeling",
            "INDEX_RELABELING",
            r"using the property that the Berry curvature is opposite for the two bands ($\Omega_{ab}^2=-\Omega_{ab}^1$)",
            ["D-77"],
            ["D-78"],
            executable=True,
            left=load("sigma_m1_simplified.txt"),
            right=load("sigma_m1_band_sum.txt"),
            subst={"Oab2": "-Oab1", "Oac2": "-Oac1"},
            condition=r"substitute $\Omega^2=-\Omega^1$",
            regression="D.Omega2-relabel",
            tex_lines=[923, 930],
        ),
        R(
            "Eq. (D-79)",
            r"$1/4!=1/24$ in $T_4$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"$T_4=\sum_n \frac{1}{4!}v_n^a v_n^b v_n^c f_n^{(4)}=\sum_n \frac{1}{24}v_n^a v_n^b v_n^c f_n^{(4)}$",
            ["D-79"],
            ["D-79"],
            executable=True,
            left="(1/(4*3*2*1))*va*vb*vc*f4",
            right="Rational(1,24)*va*vb*vc*f4",
            tex_lines=[941, 945],
        ),
        R(
            "Eq. (D-81) -> Eq. (D-82)",
            r"$T_{3A}$ prefactor $2\epsilon_{12}^2/(48\epsilon_{12})=\epsilon_{12}/24$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"using the Metric-Velocity Relation ... for $T_{3A}$",
            ["D-81"],
            ["D-82"],
            executable=True,
            left="(2*e12**2)/(48*e12)*((v1c*gab + v1b*gac)*f13 - (v2c*gab + v2b*gac)*f23)",
            right="(e12/24)*((gab*v1c + gac*v1b)*f13 - (gab*v2c + gac*v2b)*f23)",
            condition=r"after substituting the metric-velocity pair into $K_{nA}$",
            tex_lines=[963, 970],
        ),
        R(
            "Eq. (D-81) -> Eq. (D-83)",
            r"$T_{3B}$ prefactor from $K_{nB}$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"for $T_{3B}$",
            ["D-81"],
            ["D-83"],
            executable=True,
            left="(1/(48*e12))*(((v11ac*v1b + v11ab*v1c)*e12)*f13 - ((-(v22ac*v2b + v22ab*v2c)*e12))*f23)",
            right="(e12/(48*e12))*((v11ac*v1b + v11ab*v1c)*f13 + (v22ac*v2b + v22ab*v2c)*f23)",
            tex_lines=[972, 978],
        ),
        R(
            "Eq. (D-83) -> Eq. (D-84)",
            r"insert diagonal second-derivative identity into $T_{3B}$",
            "definition",
            "DEFINITION_INSERTION",
            r"we utilize the Diagonal Second Derivative Identity",
            ["D-83"],
            ["D-84"],
            tex_lines=[980, 985],
        ),
        R(
            "Eq. (D-84) -> Eqs. (D-85), (D-86)",
            r"$T_{3B}^{\mathrm{intra}}$ and $T_{3B}^{\mathrm{inter}}$",
            "definition",
            "SPLIT_PARENT",
            r"and separate this into intraband derivative terms and geometric terms",
            ["D-84"],
            ["D-85", "D-86"],
            tex_lines=[985, 996],
        ),
        R(
            "Eqs. (D-82), (D-86)",
            r"$T_{3B}^{\mathrm{inter}}=-T_{3A}$",
            "substitution",
            "ALGEBRAIC_EQUIVALENCE",
            r"since $\epsilon_{21}=-\epsilon_{12}$, we find $T_{3B}^{\mathrm{inter}}=-T_{3A}$",
            ["D-82", "D-86"],
            ["D-86"],
            executable=True,
            left="(-Rational(2,48))*(e12*(gac*v1b + gab*v1c)*f13 + e21*(gac*v2b + gab*v2c)*f23)",
            right="-((e12/24)*((gab*v1c + gac*v1b)*f13 - (gab*v2c + gac*v2b)*f23))",
            subst={"e21": "-e12"},
            condition=r"substitute $\epsilon_{21}=-\epsilon_{12}$",
            tex_lines=[997, 997],
        ),
        R(
            "Eqs. (D-82), (D-85), (D-86) -> Eq. (D-87)",
            r"$T_3=T_{3B}^{\mathrm{intra}}$ after geometric cancel",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"the geometric contributions cancel exactly: $T_3=T_{3A}+T_{3B}=T_{3B}^{\mathrm{intra}}$",
            ["D-82", "D-85", "D-86"],
            ["D-87"],
            tex_lines=[998, 1005],
        ),
        R(
            "Eq. (D-88) -> Eq. (D-89)",
            r"$T_2$ metric substitution",
            "substitution",
            "ALGEBRAIC_EQUIVALENCE",
            r"applying the Metric-Velocity Relation",
            ["D-88"],
            ["D-89"],
            executable=True,
            left="(1/(4*e12**2))*va*(v21b*v12c + v12b*v21c)*fn2",
            right="Rational(1,2)*gbc*va*fn2",
            subst={"v21b*v12c + v12b*v21c": "2*e12**2*gbc"},
            condition=r"substitute $v_{21}^b v_{12}^c+v_{12}^b v_{21}^c=2\epsilon_{12}^2 g_{bc}$",
            tex_lines=[1011, 1022],
        ),
        R(
            "Eq. (D-91) -> Eq. (D-92)",
            r"$T_1$ coefficient $C_1$ regroup and metric",
            "substitution",
            "ALGEBRAIC_EQUIVALENCE",
            r"we reorganize $C_1$ and apply the Metric-Velocity Relation",
            ["D-91"],
            ["D-92"],
            executable=True,
            left="v1c*(v21a*v12b + v12a*v21b) + v1b*(v21a*v12c + v12a*v21c) - v1a*(v21b*v12c + v12b*v21c)",
            right="v1c*(2*e12**2*gab) + v1b*(2*e12**2*gac) - v1a*(2*e12**2*gbc)",
            subst={
                "v21a*v12b + v12a*v21b": "2*e12**2*gab",
                "v21a*v12c + v12a*v21c": "2*e12**2*gac",
                "v21b*v12c + v12b*v21c": "2*e12**2*gbc",
            },
            condition=r"substitute the metric-velocity pair",
            tex_lines=[1040, 1046],
        ),
        R(
            "Eqs. (D-90), (D-92) -> Eq. (D-93)",
            r"$T_1$ prefactor $2\epsilon_{12}^2/(2\epsilon_{12}^3)=1/\epsilon_{12}$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"$C_2$ follows similarly. Substituting these back into $T_1$",
            ["D-90", "D-92"],
            ["D-93"],
            executable=True,
            left="(2*e12**2)/(2*e12**3)*((v1c*gab + v1b*gac - v1a*gbc)*f1p - (v2c*gab + v2b*gac - v2a*gbc)*f2p)",
            right="(1/e12)*((v1c*gab + v1b*gac - v1a*gbc)*f1p - (v2c*gab + v2b*gac - v2a*gbc)*f2p)",
            tex_lines=[1047, 1054],
        ),
        R(
            "Eq. (D-95) -> Eq. (D-96)",
            r"$A=6\epsilon_{12}^2 g_{bc}(v_2^a-v_1^a)$",
            "substitution",
            "ALGEBRAIC_EQUIVALENCE",
            r"for Part A and Part B we use Metric-Velocity Relation",
            ["D-95"],
            ["D-96"],
            executable=True,
            left="3*(v2a - v1a)*(v21b*v12c + v12b*v21c)",
            right="6*e12**2*gbc*(v2a - v1a)",
            subst={"v21b*v12c + v12b*v21c": "2*e12**2*gbc"},
            condition=r"substitute $v_{21}^b v_{12}^c+v_{12}^b v_{21}^c=2\epsilon_{12}^2 g_{bc}$",
            tex_lines=[1076, 1081],
        ),
        R(
            "Eq. (D-95) -> Eq. (D-97)",
            r"$B=2\epsilon_{12}^2[g_{ac}(v_2^b-v_1^b)+g_{ab}(v_2^c-v_1^c)]$",
            "substitution",
            "ALGEBRAIC_EQUIVALENCE",
            r"for Part A and Part B we use Metric-Velocity Relation",
            ["D-95"],
            ["D-97"],
            executable=True,
            left="(v2b-v1b)*(v21a*v12c + v12a*v21c) + (v2c-v1c)*(v21a*v12b + v12a*v21b)",
            right="2*e12**2*(gac*(v2b-v1b) + gab*(v2c-v1c))",
            subst={
                "v21a*v12c + v12a*v21c": "2*e12**2*gac",
                "v21a*v12b + v12a*v21b": "2*e12**2*gab",
            },
            condition=r"substitute the metric-velocity pair",
            tex_lines=[1082, 1087],
        ),
        R(
            "Eq. (D-98) -> Eq. (D-99)",
            r"$S_{ac;b}+S_{ab;c}$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"we consider the symmetric combination required for $E$",
            ["D-98"],
            ["D-99"],
            tex_lines=[1096, 1102],
        ),
        R(
            "Eq. (D-99) -> Eq. (D-100)",
            r"metric-velocity inside $\partial_a(v_{21}^c v_{12}^b+\cdots)$",
            "substitution",
            "ALGEBRAIC_EQUIVALENCE",
            r"we use Metric-Velocity Relation for the term inside the derivative",
            ["D-99"],
            ["D-100"],
            executable=True,
            left="v21c*v12b + v21b*v12c",
            right="2*e12**2*gbc",
            subst={"v21c*v12b + v21b*v12c": "2*e12**2*gbc"},
            condition=r"substitute the metric-velocity pair",
            tex_lines=[1103, 1108],
        ),
        R(
            "Eq. (D-101) -> Eq. (D-102)",
            r"two-band commutators into $K_{ab;c}$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"substituting these into the definition of $K_{ab;c}$",
            ["D-101"],
            ["D-102"],
            tex_lines=[1116, 1122],
        ),
        R(
            "Eq. (D-103)",
            r"$P_{\mathrm{gauge}}=0$ by commuting velocities",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"since the velocity matrix elements commute, the terms inside the bracket cancel exactly: $P_{\mathrm{gauge}}=0$",
            ["D-103"],
            ["D-103"],
            executable=True,
            left="(A11a - A22a)*((v12c*v21b - v21c*v12b) + (v12b*v21c - v21b*v12c))",
            right="0",
            tex_lines=[1123, 1128],
        ),
        R(
            "Eq. (D-105)",
            r"$A_{12}^a v_{21}^b-A_{21}^a v_{12}^b=-2i\epsilon_{12}g_{ab}$",
            "substitution",
            "ALGEBRAIC_EQUIVALENCE",
            r"we evaluate the bracketed terms using the Feynman-Hellmann identity",
            ["D-105"],
            ["D-105"],
            executable=True,
            left="A12a*(-I*e12*A21b) - A21a*(-I*e21*A12b)",
            right="-2*I*e12*gab",
            subst={"e21": "-e12", "A12a*A21b + A21a*A12b": "2*gab"},
            condition=r"Feynman--Hellmann and $g_{ab}=\mathrm{Re}(A_{12}^a A_{21}^b)$; $\epsilon_{21}=-\epsilon_{12}$",
            tex_lines=[1136, 1142],
        ),
        R(
            "Eqs. (D-104), (D-105) -> Eq. (D-106)",
            r"$K_{abc}=-2i\epsilon_{12}[(v_2^c-v_1^c)g_{ab}+\cdots]$",
            "substitution",
            "ALGEBRAIC_EQUIVALENCE",
            r"substituting this back into $K_{abc}$",
            ["D-104", "D-105"],
            ["D-106"],
            executable=True,
            left="(v2c-v1c)*(-2*I*e12*gab) + (v2b-v1b)*(-2*I*e12*gac)",
            right="-2*I*e12*((v2c-v1c)*gab + (v2b-v1b)*gac)",
            tex_lines=[1143, 1148],
        ),
        R(
            "Eqs. (D-100), (D-106) -> Eq. (D-107)",
            r"$-i K_{abc}$ becomes $-2\epsilon_{12}[\cdots]$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"now we assemble the expression for $S_{ac;b}+S_{ab;c}$",
            ["D-100", "D-106"],
            ["D-107"],
            executable=True,
            left="-I*(-2*I*e12*((v2c-v1c)*gab + (v2b-v1b)*gac))",
            right="-2*e12*(gab*(v2c-v1c) + gac*(v2b-v1b))",
            tex_lines=[1149, 1154],
        ),
        R(
            "Eq. (D-108)",
            r"$\partial_a(2\epsilon_{12}^2 g_{bc})=4\epsilon_{12}(v_1^a-v_2^a)g_{bc}+2\epsilon_{12}^2\partial_a g_{bc}$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"we expand the derivative term, using $\partial_a\epsilon_{12}=v_1^a-v_2^a$",
            ["D-108"],
            ["D-108"],
            executable=True,
            left="4*e12*dae12*gbc + 2*e12**2*dagbc",
            right="4*e12*(v1a-v2a)*gbc + 2*e12**2*dagbc",
            subst={"dae12": "v1a - v2a"},
            condition=r"substitute $\partial_a\epsilon_{12}=v_1^a-v_2^a$",
            tex_lines=[1155, 1160],
        ),
        R(
            "Eqs. (D-107), (D-108) -> Eq. (D-109)",
            r"$E=(S_{ac;b}+S_{ab;c})\epsilon_{12}$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"the complete expression for $E=(S_{ac;b}+S_{ab;c})\epsilon_{12}$ is",
            ["D-107", "D-108"],
            ["D-109"],
            executable=True,
            left="(4*e12*(v1a-v2a)*gbc + 2*e12**2*dagbc - 2*e12*(gab*(v2c-v1c) + gac*(v2b-v1b)))*e12",
            right="4*e12**2*(v1a-v2a)*gbc + 2*e12**3*dagbc - 2*e12**2*(gab*(v2c-v1c) + gac*(v2b-v1b))",
            tex_lines=[1161, 1167],
        ),
        R(
            "Eqs. (D-96), (D-97), (D-109) -> Eq. (D-110)",
            r"$C_0=A+B+E$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"we sum the results $A$, $B$, and $E$",
            ["D-96", "D-97", "D-109"],
            ["D-110"],
            executable=True,
            left="6*e12**2*gbc*(v2a-v1a) + 2*e12**2*(gac*(v2b-v1b)+gab*(v2c-v1c)) + (4*e12**2*(v1a-v2a)*gbc + 2*e12**3*dagbc - 2*e12**2*(gab*(v2c-v1c)+gac*(v2b-v1b)))",
            right="6*e12**2*gbc*(v2a-v1a) + 2*e12**2*(gac*(v2b-v1b)+gab*(v2c-v1c)) + 4*e12**2*(v1a-v2a)*gbc + 2*e12**3*dagbc - 2*e12**2*(gab*(v2c-v1c)+gac*(v2b-v1b))",
            tex_lines=[1168, 1174],
        ),
        R(
            "Eq. (D-110) -> Eq. (D-111)",
            r"$C_0$ grouped by $g_{bc},g_{ac},g_{ab}$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"we group the terms by the geometric quantities",
            ["D-110"],
            ["D-111"],
            executable=True,
            left="6*e12**2*gbc*(v2a-v1a) + 2*e12**2*(gac*(v2b-v1b)+gab*(v2c-v1c)) + 4*e12**2*(v1a-v2a)*gbc + 2*e12**3*dagbc - 2*e12**2*(gab*(v2c-v1c)+gac*(v2b-v1b))",
            right="e12**2*gbc*(6*(v2a-v1a)+4*(v1a-v2a)) + e12**2*gac*(2*(v2b-v1b)-2*(v2b-v1b)) + e12**2*gab*(2*(v2c-v1c)-2*(v2c-v1c)) + 2*e12**3*dagbc",
            tex_lines=[1175, 1182],
        ),
        R(
            "Eq. (D-111) -> Eq. (D-112)",
            r"$g_{ac}$ and $g_{ab}$ coefficients cancel",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"the terms proportional to $g_{ac}$ and $g_{ab}$ cancel exactly",
            ["D-111"],
            ["D-112"],
            executable=True,
            left="e12**2*gbc*(6*(v2a-v1a)+4*(v1a-v2a)) + e12**2*gac*(2*(v2b-v1b)-2*(v2b-v1b)) + e12**2*gab*(2*(v2c-v1c)-2*(v2c-v1c)) + 2*e12**3*dagbc",
            right="2*e12**2*gbc*(v2a-v1a) + 2*e12**3*dagbc",
            tex_lines=[1183, 1188],
        ),
        R(
            "Eqs. (D-94), (D-112) -> Eq. (D-113)",
            r"$T_0$ after simplified $C_0$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"substituting the simplified $C_0$ back into $T_0$",
            ["D-94", "D-112"],
            ["D-113"],
            executable=True,
            left="(f1-f2)/(2*e12**4)*(2*e12**2*gbc*(v2a-v1a) + 2*e12**3*dagbc)",
            right="(f1-f2)*(gbc*(v2a-v1a)/e12**2 + dagbc/e12)",
            tex_lines=[1190, 1195],
        ),
        R(
            "Eq. (D-113) -> Eq. (D-114)",
            r"$T_0=(f_1-f_2)\partial_a(g_{bc}/\epsilon_{12})$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"since $v_2^a-v_1^a=-(\partial_a\epsilon_{12})$, this expression is recognized as the quotient rule",
            ["D-113"],
            ["D-114"],
            executable=True,
            left="gbc*(v2a-v1a)/e12**2 + dagbc/e12",
            right="(dagbc*e12 - gbc*dae12)/e12**2",
            subst={"v2a - v1a": "-dae12"},
            condition=r"substitute $v_2^a-v_1^a=-\partial_a\epsilon_{12}$",
            tex_lines=[1196, 1202],
        ),
        R(
            "local Leibniz rule for Eqs. (D-114)->(D-119) and (D-123)->(D-124)",
            r"$\partial_k(uv)=(\partial_k u)v+u(\partial_k v)$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            "local product rule used in Brillouin-zone integration by parts",
            ["D-114"],
            ["D-119"],
            executable=True,
            left="diff(u(k)*v(k), k)",
            right="diff(u(k), k)*v(k) + u(k)*diff(v(k), k)",
            regression="D.leibniz-product-rule",
            helper=True,
            tex_lines=[1208, 1208],
        ),
        R(
            "Eq. (D-114) -> Eq. (D-119)",
            r"$T_0$ BZ integration by parts",
            "BZ integration by parts",
            "BZ_PERIODIC_INTEGRATION_BY_PARTS",
            r"we apply IBP to $T_0$ to transform the Fermi sea term to the Fermi surface",
            ["D-114"],
            ["D-119"],
            parent_status="CERTIFIED_BY_RULE",
            condition=r"periodic Brillouin-zone torus; local Leibniz identity checked exactly",
            regression="D.T0-ibp-global",
            tex_lines=[1241, 1247],
        ),
        R(
            "Eq. (D-119)",
            r"$T_0$ local sign algebra after IBP",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"$T_0 \xrightarrow{\mathrm{IBP}} g_{bc}((v_2^a f_2'-v_1^a f_1')/\epsilon_{12})$",
            ["D-119"],
            ["D-119"],
            executable=True,
            left=load("T0_chain.txt"),
            right=load("T0_surface.txt"),
            regression="D.T0-local-sign",
            tex_lines=[1243, 1247],
        ),
        R(
            "Eq. (D-87) -> Eq. (D-115)",
            r"$T_3$ IBP",
            "BZ integration by parts",
            "BZ_PERIODIC_INTEGRATION_BY_PARTS",
            r"we apply IBP to $T_3$ with respect to $k_a$",
            ["D-87"],
            ["D-115"],
            parent_status="CERTIFIED_BY_RULE",
            condition=r"periodic Brillouin-zone torus; local Leibniz identity checked exactly",
            tex_lines=[1212, 1218],
        ),
        R(
            "Eq. (D-115) -> Eq. (D-116)",
            r"chain rule $\partial_a f_n^{(3)}=f_n^{(4)} v_n^a$; $T_3=-\frac12 T_4$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"using the chain rule $\partial_a f_n^{(3)}=f_n^{(4)} v_n^a$",
            ["D-115"],
            ["D-116"],
            executable=True,
            left="-Rational(1,48)*va*vb*vc*f4",
            right="-Rational(1,2)*Rational(1,24)*va*vb*vc*f4",
            tex_lines=[1218, 1223],
        ),
        R(
            "Eqs. (D-79), (D-116) -> Eq. (D-117)",
            r"$\sigma^{\mathrm{kin}}=T_3+T_4=\frac12 T_4$",
            "substitution",
            "ALGEBRAIC_EQUIVALENCE",
            r"the total intraband contribution simplifies to $\sigma^{\mathrm{kin}}=T_3+T_4=\frac12 T_4$",
            ["D-79", "D-116"],
            ["D-117"],
            executable=True,
            left="Rational(1,24)*va*vb*vc*f4 + (-Rational(1,48)*va*vb*vc*f4)",
            right="Rational(1,24)*va*vb*vc*f04",
            subst={"f4": "2*f04"},
            condition=r"substitute $f_n^{(4)}=2f_{0,n}^{(4)}$ on the last equality",
            tex_lines=[1224, 1232],
        ),
        R(
            "Eq. (D-117) -> Eq. (D-118)",
            r"further BZ IBP $\sigma^{\mathrm{kin}}\propto(\partial_a\partial_b\partial_c\epsilon_n)f_0^{(2)}$",
            "BZ integration by parts",
            "BZ_PERIODIC_INTEGRATION_BY_PARTS",
            r"to improve numerical stability, we can reduce the order of the derivative ... by integration by parts",
            ["D-117"],
            ["D-118"],
            parent_status="CERTIFIED_BY_RULE",
            condition=r"periodic Brillouin-zone torus; local Leibniz identity checked exactly",
            tex_lines=[1236, 1239],
        ),
        R(
            "Eqs. (D-119), (D-93) -> Eq. (D-120)",
            r"$T_0+T_1$ combined $f'$ terms",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"we combine the $f'$ terms from $T_0$ and $T_1$",
            ["D-119", "D-93"],
            ["D-120"],
            tex_lines=[1248, 1255],
        ),
        R(
            "Eq. (D-120) -> Eq. (D-121)",
            r"$T_0+T_1$ regroup by $f_1',f_2'$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"grouping terms by $f_1'$ and $f_2'$",
            ["D-120"],
            ["D-121"],
            executable=True,
            left=load("T0T1_mixed.txt"),
            right=load("T0T1_grouped.txt"),
            regression="D.T0T1-regroup",
            tex_lines=[1256, 1261],
        ),
        R(
            "Eqs. (D-89), (D-121) -> Eq. (D-122)",
            r"$\sigma^{\mathrm{geo}}=T_2+(T_0+T_1)$",
            "bookkeeping",
            "BOOKKEEPING",
            r"the total geometric contribution, including $T_2$, is",
            ["D-89", "D-121"],
            ["D-122"],
            tex_lines=[1262, 1267],
        ),
        R(
            "Eq. (D-89) -> Eq. (D-123)",
            r"$v_n^a f_n^{(2)}=\partial_a(f_n')$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"we use the identity $v_n^a f_n^{(2)}=\partial_a(f_n')$",
            ["D-89"],
            ["D-123"],
            tex_lines=[1268, 1273],
        ),
        R(
            "Eq. (D-123) -> Eq. (D-124)",
            r"$T_2$ BZ integration by parts",
            "BZ integration by parts",
            "BZ_PERIODIC_INTEGRATION_BY_PARTS",
            r"applying IBP w.r.t $k_a$",
            ["D-123"],
            ["D-124"],
            parent_status="CERTIFIED_BY_RULE",
            condition=r"periodic Brillouin-zone torus; local Leibniz identity checked exactly",
            regression="D.T2-ibp-global",
            tex_lines=[1274, 1279],
        ),
        R(
            "Eqs. (D-122), (D-124) -> Eq. (D-125)",
            r"$\sigma^{\mathrm{geo}}$ after declared $T_2$ IBP",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"substituting this transformed $T_2$ and $(T_0+T_1)$ into $\sigma^{\mathrm{geo}}$",
            ["D-122", "D-124"],
            ["D-125"],
            executable=True,
            left=load("geo_T2_plus_T0T1.txt"),
            right=load("geo_fnp.txt"),
            regression="D.geo-T2-subst",
            tex_lines=[1282, 1288],
        ),
        R(
            "Eq. (D-125) -> Eq. (D-126)",
            r"$\epsilon_{21}=-\epsilon_{12}$ symmetrization",
            "substitution",
            "ALGEBRAIC_EQUIVALENCE",
            r"we rewrite the expression for band 2 using the energy denominator $\epsilon_{21}=-\epsilon_{12}$",
            ["D-125"],
            ["D-126"],
            executable=True,
            left=load("geo_fnp_subst.txt"),
            right=load("geo_eps21.txt"),
            subst={"e21": "-e12"},
            condition=r"substitute $\epsilon_{21}=-\epsilon_{12}$",
            regression="D.eps21-symmetrize",
            tex_lines=[1289, 1295],
        ),
        R(
            "Eq. (D-126) -> Eq. (D-127)",
            r"compact $n,\bar n$ form with $f_n'=2f_{0,n}'$",
            "index relabeling",
            "INDEX_RELABELING",
            r"this can be written compactly using $\epsilon_{n\bar n}$; $f_n'=2f_{0,n}'$",
            ["D-126"],
            ["D-127"],
            executable=True,
            left=load("geo_eps21_fprime.txt"),
            right=load("geo_nbar.txt"),
            subst={"f1p": "2*f01p", "f2p": "2*f02p"},
            condition=r"substitute $f_n'=2f_{0,n}'$",
            regression="D.compact-nbar",
            tex_lines=[1296, 1305],
        ),
    ]


def extend_e() -> list[dict]:
    return [
        R(
            "Eq. (E-128)",
            r"multiband $v_{nn}^{ab}$ identity",
            "definition",
            "DEFINITION_INSERTION",
            r"multiband diagonal second derivative",
            ["E-128"],
            ["E-128"],
            regression="E.diag-2nd",
            tex_lines=[1334, 1337],
        ),
        R(
            "Eq. (E-130) -> Eq. (E-131)",
            r"multiband $\sigma^{(-2)}$ after diagonal $v_{nn}^{ab}$",
            "definition",
            "DEFINITION_INSERTION",
            r"by using the property of Diagonal Second Derivative, the expression can be significantly simplified",
            ["E-130"],
            ["E-131"],
            tex_lines=[1362, 1372],
        ),
        R(
            "Eq. (E-132) -> Eq. (E-133)",
            r"multiband $\sigma^{(-1)}$ via curvature-velocity",
            "definition",
            "DEFINITION_INSERTION",
            r"by utilizing the multiband curvature-velocity relation",
            ["E-132"],
            ["E-133"],
            tex_lines=[1384, 1390],
        ),
        R(
            "Eq. (E-134)",
            r"$\sigma^{(0)}=T_0+\cdots+T_4$",
            "definition",
            "SPLIT_PARENT",
            r"we expand $\sigma_{abc}^{(0)}$ in powers of the inverse temperature $\beta$",
            ["E-134"],
            ["E-134"],
            tex_lines=[1395, 1398],
        ),
        R(
            "Eq. (E-135)",
            r"$T_4=\frac{1}{4!}\sum_n v_n^a v_n^b v_n^c f_n^{(4)}$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"this contribution is proportional to the fourth derivative",
            ["E-135"],
            ["E-135"],
            executable=True,
            left="(1/(4*3*2*1))*va*vb*vc*f4",
            right="Rational(1,24)*va*vb*vc*f4",
            tex_lines=[1402, 1408],
        ),
        R(
            "Eq. (E-136) -> Eq. (E-137)",
            r"multiband $T_3$ after diagonal $v_{nn}^{ab}$",
            "definition",
            "DEFINITION_INSERTION",
            r"then, we utilize the property of Diagonal Second Derivative",
            ["E-136"],
            ["E-137"],
            tex_lines=[1418, 1424],
        ),
        R(
            "Eq. (E-138) -> Eq. (E-139)",
            r"multiband $T_2$ via metric-velocity",
            "definition",
            "DEFINITION_INSERTION",
            r"by using the Multiband Metric-Velocity Relation",
            ["E-138"],
            ["E-139"],
            tex_lines=[1434, 1437],
        ),
        R(
            "Eq. (E-140) -> Eq. (E-141)",
            r"multiband $T_1$ via $\mathcal{G}$",
            "definition",
            "DEFINITION_INSERTION",
            r"applying the Multiband Band-renormalized Metric-Velocity Relation",
            ["E-140"],
            ["E-141"],
            tex_lines=[1446, 1452],
        ),
        R(
            "Eq. (E-142) -> Eq. (E-143)",
            r"multiband remainder $\mathcal{M}=0$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"we collect all multiband contributions (denoted as $\mathcal{M}$) ... $=0$",
            ["E-142"],
            ["E-143"],
            tex_lines=[1469, 1483],
        ),
        R(
            "Eqs. (E-142), (E-143) -> Eq. (E-144)",
            r"$T_0$ reduces to two-band index terms",
            "bookkeeping",
            "BOOKKEEPING",
            r"consequently, only terms involving two-band indices contribute",
            ["E-142", "E-143"],
            ["E-144"],
            tex_lines=[1485, 1493],
        ),
        R(
            "Eq. (E-144) -> Eq. (E-145)",
            r"shift-vector identity in $T_0$",
            "definition",
            "DEFINITION_INSERTION",
            r"we utilize the properties of shift vector",
            ["E-144"],
            ["E-145"],
            tex_lines=[1494, 1500],
        ),
        R(
            "Eq. (E-145) -> Eq. (E-146)",
            r"$T_0=\sum_n f_n\partial_a\mathcal{G}_n^{bc}$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"by further applying the Feynman-Hellmann identity ... the final expression is shown to be proportional to the derivative of the band-renormalized quantum metric",
            ["E-145"],
            ["E-146"],
            tex_lines=[1502, 1509],
        ),
        R(
            "Eq. (E-137) -> Eq. (E-147)",
            r"multiband $T_3$ IBP $=-\frac12 T_4$",
            "BZ integration by parts",
            "BZ_PERIODIC_INTEGRATION_BY_PARTS",
            r"by performing IBP on $T_3$ with respect to $k_a$, we obtain",
            ["E-137"],
            ["E-147"],
            parent_status="CERTIFIED_BY_RULE",
            condition=r"periodic Brillouin-zone torus; local Leibniz identity checked exactly",
            tex_lines=[1515, 1518],
        ),
        R(
            "Eqs. (E-135), (E-147) -> Eq. (E-148)",
            r"$\sigma^{\mathrm{kin}}=\frac12 T_4$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"summing the resulting terms yields",
            ["E-135", "E-147"],
            ["E-148"],
            executable=True,
            left="Rational(1,24)*va*vb*vc*f4 + (-Rational(1,2)*Rational(1,24)*va*vb*vc*f4)",
            right="Rational(1,24)*va*vb*vc*f04",
            subst={"f4": "2*f04"},
            condition=r"local $T_3=-\frac12 T_4$ after declared IBP; substitute $f_n^{(4)}=2f_{0,n}^{(4)}$",
            tex_lines=[1520, 1525],
        ),
        R(
            "Eq. (E-146) -> Eq. (E-149)",
            r"multiband $T_0$ IBP",
            "BZ integration by parts",
            "BZ_PERIODIC_INTEGRATION_BY_PARTS",
            r"first, we apply IBP to $T_0$",
            ["E-146"],
            ["E-149"],
            parent_status="CERTIFIED_BY_RULE",
            condition=r"periodic Brillouin-zone torus; local Leibniz identity checked exactly",
            tex_lines=[1528, 1532],
        ),
        R(
            "Eq. (E-139) -> Eq. (E-150)",
            r"multiband $T_2$ IBP",
            "BZ integration by parts",
            "BZ_PERIODIC_INTEGRATION_BY_PARTS",
            r"next, performing IBP on $T_2$ leads to",
            ["E-139"],
            ["E-150"],
            parent_status="CERTIFIED_BY_RULE",
            condition=r"periodic Brillouin-zone torus; local Leibniz identity checked exactly",
            tex_lines=[1534, 1537],
        ),
        R(
            "Eqs. (E-141), (E-149), (E-150) -> Eq. (E-151)",
            r"multiband $\sigma^{\mathrm{geo}}$ assembly",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"combining the above contributions with $T_1$, we arrive at the final expression",
            ["E-141", "E-149", "E-150"],
            ["E-151"],
            executable=True,
            left="-Rational(1,2)*f1p*dag + f1p*(vb*Gac + vc*Gab - va*Gbc) - f1p*va*Gbc",
            right="f1p*(vb*Gac + vc*Gab - 2*va*Gbc - dag/2)",
            tex_lines=[1539, 1546],
        ),
    ]


def extend_f() -> list[dict]:
    return [
        R(
            "Eq. (F-152)",
            r"SHG $\Gamma$ expansion",
            "asymptotic expansion",
            "ASYMPTOTIC_CLAIM",
            r"subsequently perform a relaxation-time expansion around $\Gamma=0$",
            ["F-152"],
            ["F-152"],
            parent_status="UNKNOWN_REMAINDER",
            condition=r"author-declared $O(\Gamma)$ remainder",
            tex_lines=[1563, 1565],
        ),
        R(
            "Eq. (F-153) -> Eq. (F-154)",
            r"SHG $\sigma^{(-2)}$ after $v_{nn}^{ab}$ and IBP",
            "BZ integration by parts",
            "BZ_PERIODIC_INTEGRATION_BY_PARTS",
            r"by applying the properties of the diagonal second derivative and performing integration by parts",
            ["F-153"],
            ["F-154"],
            parent_status="CERTIFIED_BY_RULE",
            condition=r"periodic Brillouin-zone torus; local Leibniz identity checked exactly",
            tex_lines=[1576, 1584],
        ),
        R(
            "Eq. (F-155) -> Eq. (F-156)",
            r"SHG $\sigma^{(-1)}$ via curvature-velocity",
            "definition",
            "DEFINITION_INSERTION",
            r"utilizing the multiband curvature-velocity relation",
            ["F-155"],
            ["F-156"],
            tex_lines=[1594, 1600],
        ),
        R(
            "Eq. (F-157)",
            r"$\sigma^{\mathrm{SHG}(0)}=T_0^{\mathrm{SHG}}+\cdots+T_4^{\mathrm{SHG}}$",
            "definition",
            "SPLIT_PARENT",
            r"the SHG $\Gamma^0$ term is expanded in powers of $\beta$",
            ["F-157"],
            ["F-157"],
            tex_lines=[1605, 1607],
        ),
        R(
            "Eq. (E-135) -> Eq. (F-158)",
            r"$T_4^{\mathrm{SHG}}=-T_4$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"the fourth-order SHG contribution is the negative of the one of the rectified current",
            ["E-135"],
            ["F-158"],
            executable=True,
            left="-Rational(1,24)*va*vb*vc*f4",
            right="-((1/(4*3*2*1))*va*vb*vc*f4)",
            tex_lines=[1610, 1613],
        ),
        R(
            "Eq. (F-159) -> Eq. (F-160)",
            r"$T_3^{\mathrm{SHG}}$ after diagonal $v_{nn}^{ab}$",
            "definition",
            "DEFINITION_INSERTION",
            r"by utilizing the properties of the Diagonal Second Derivative",
            ["F-159"],
            ["F-160"],
            tex_lines=[1623, 1629],
        ),
        R(
            "Eq. (F-161)",
            r"$T_2^{\mathrm{SHG}}=T_2$",
            "bookkeeping",
            "BOOKKEEPING",
            r"the second-order SHG term $T_2^{\mathrm{SHG}}$ is found to be identical to its counterpart in the rectified current",
            ["F-161"],
            ["F-161"],
            tex_lines=[1633, 1637],
        ),
        R(
            "Eq. (F-162) -> Eq. (F-163)",
            r"$T_1^{\mathrm{SHG}}$ via $\mathcal{G}$",
            "definition",
            "DEFINITION_INSERTION",
            r"by invoking the multiband band-renormalized metric-velocity relation",
            ["F-162"],
            ["F-163"],
            tex_lines=[1646, 1652],
        ),
        R(
            "Eqs. (F-164)--(F-168) -> Eq. (F-157)",
            r"$T_0^{\mathrm{SHG}}$ split into five pieces",
            "definition",
            "SPLIT_PARENT",
            r"for clarity, we decompose the initial expression into five distinct components",
            ["F-164", "F-165", "F-166", "F-167", "F-168"],
            ["F-157"],
            tex_lines=[1656, 1696],
        ),
        R(
            "Eq. (F-165) -> Eq. (F-169)",
            r"expand off-diagonal $v_{nm}^{ab}$ in $T_{0,2}^{\mathrm{SHG}}$",
            "definition",
            "DEFINITION_INSERTION",
            r"starting from $T_{0,2}^{\mathrm{SHG}}$, we expand the Off-diagonal Second Derivatives",
            ["F-165"],
            ["F-169"],
            tex_lines=[1697, 1720],
        ),
        R(
            "Eqs. (F-166), (F-169) -> Eq. (F-171)",
            r"$T_{0,2}+T_{0,3}$ two-band vs multiband split",
            "bookkeeping",
            "SPLIT_PARENT",
            r"by combining $T_{0,2}^{\mathrm{SHG}}$ and $T_{0,3}^{\mathrm{SHG}}$, we can decompose ... into a two-band term and a multiband contribution",
            ["F-166", "F-169"],
            ["F-171"],
            tex_lines=[1732, 1757],
        ),
        R(
            "Eqs. (F-167), (F-168), (F-171) -> Eq. (F-172)",
            r"SHG multiband remainder $\mathcal{M}$",
            "bookkeeping",
            "BOOKKEEPING",
            r"at this stage, we shall now group the multiband contributions",
            ["F-167", "F-168", "F-171"],
            ["F-172"],
            tex_lines=[1759, 1784],
        ),
        R(
            "Eq. (F-172) -> Eq. (F-173)",
            r"SHG $\mathcal{M}=0$ after dummy-index reclassification",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"upon summing the coefficients of these matrix products, we find that the total multiband contribution vanishes identically",
            ["F-172"],
            ["F-173"],
            tex_lines=[1785, 1794],
        ),
        R(
            "Eqs. (F-164), (F-171), (F-173) -> Eq. (F-174)",
            r"$T_0^{\mathrm{SHG}}$ reduces to two-band terms",
            "bookkeeping",
            "BOOKKEEPING",
            r"the vanishing of $\mathcal{M}$ ... $T_0^{\mathrm{SHG}}$ reduces to a combination of two-band terms",
            ["F-164", "F-171", "F-173"],
            ["F-174"],
            tex_lines=[1796, 1807],
        ),
        R(
            "Eq. (F-174) -> Eq. (F-175)",
            r"Feynman--Hellmann rewrite of $T_0^{\mathrm{SHG}}$",
            "definition",
            "DEFINITION_INSERTION",
            r"by invoking the Feynman-Hellmann identity, this expression can be further transformed",
            ["F-174"],
            ["F-175"],
            tex_lines=[1808, 1815],
        ),
        R(
            "Eq. (F-175) -> Eq. (F-176)",
            r"$T_0^{\mathrm{SHG}}=-\sum_n f_n(2\partial_c\mathcal{G}^{ab}+\cdots)$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"these partial derivatives can be reorganized into the form of total derivatives of the band-renormalized quantum metric",
            ["F-175"],
            ["F-176"],
            tex_lines=[1816, 1822],
        ),
        R(
            "Eq. (F-160) -> Eq. (F-177)",
            r"$T_3^{\mathrm{SHG}}$ IBP using $4\partial_b\partial_c\epsilon\,\partial_a\epsilon$ identity",
            "BZ integration by parts",
            "BZ_PERIODIC_INTEGRATION_BY_PARTS",
            r"for $T_3$, we utilize the relation $4\partial_b\partial_c\epsilon_n\partial_a\epsilon_n=\cdots$ and perform IBP",
            ["F-160"],
            ["F-177"],
            parent_status="CERTIFIED_BY_RULE",
            condition=r"periodic Brillouin-zone torus; local Leibniz identity checked exactly",
            tex_lines=[1828, 1836],
        ),
        R(
            "Eqs. (F-158), (F-177) -> Eq. (F-178)",
            r"SHG $\sigma^{\mathrm{kin}}$: $-\frac1{24}+\frac{3}{48}=\frac1{48}$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"summing these contributions, we arrive at the final expression",
            ["F-158", "F-177"],
            ["F-178"],
            executable=True,
            left="-Rational(1,24)*va*vb*vc*f4 + Rational(3,48)*va*vb*vc*f4",
            right="Rational(1,48)*va*vb*vc*f4",
            tex_lines=[1837, 1845],
        ),
        R(
            "Eq. (F-176) -> Eq. (F-179)",
            r"$T_0^{\mathrm{SHG}}$ IBP",
            "BZ integration by parts",
            "BZ_PERIODIC_INTEGRATION_BY_PARTS",
            r"by performing integration by parts on $T_0^{\mathrm{SHG}}$",
            ["F-176"],
            ["F-179"],
            parent_status="CERTIFIED_BY_RULE",
            condition=r"periodic Brillouin-zone torus; local Leibniz identity checked exactly",
            tex_lines=[1848, 1854],
        ),
        R(
            "Eq. (F-161) -> Eq. (F-180)",
            r"$T_2^{\mathrm{SHG}}$ IBP",
            "BZ integration by parts",
            "BZ_PERIODIC_INTEGRATION_BY_PARTS",
            r"likewise, performing IBP on $T_2$ yields",
            ["F-161"],
            ["F-180"],
            parent_status="CERTIFIED_BY_RULE",
            condition=r"periodic Brillouin-zone torus; local Leibniz identity checked exactly",
            tex_lines=[1855, 1860],
        ),
        R(
            "Eqs. (F-163), (F-179), (F-180) -> Eq. (F-181)",
            r"SHG $\sigma^{\mathrm{geo}}$ assembly",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"summing these three components, we obtain the total geometric contribution",
            ["F-163", "F-179", "F-180"],
            ["F-181"],
            executable=True,
            left="-Rational(1,2)*f1p*dag - f1p*(vb*Gac + vc*Gab + va*Gbc) + f1p*(2*vc*Gab + 2*vb*Gac - va*Gbc)",
            right="f1p*(vb*Gac + vc*Gab - 2*va*Gbc - dag/2)",
            tex_lines=[1861, 1869],
        ),
    ]


def extend_g() -> list[dict]:
    return [
        R(
            "Eq. (G-182) -> Eq. (G-183)",
            r"open-system Schrödinger equation for $\ket{\psi_n^j}$",
            "definition",
            "DEFINITION_INSERTION",
            r"the exact equation of motion for $\ket{\psi_n^j(t)}$ is given by",
            ["G-182"],
            ["G-183"],
            tex_lines=[1884, 1890],
        ),
        R(
            "Eqs. (G-182), (G-183) -> Eq. (G-184)",
            r"$i\partial_t\rho_S=[H_S,\rho_S]-2i\Gamma\rho_S+\mathcal{S}$",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"from this, we derive the equation of motion for the reduced density matrix",
            ["G-182", "G-183"],
            ["G-184"],
            tex_lines=[1893, 1902],
        ),
        R(
            "Eq. (G-184) -> Eq. (G-185)",
            r"static-Hamiltonian approximation for $\ket{\psi_n^j}$",
            "definition",
            "DEFINITION_INSERTION",
            r"one must artificially freeze the system Hamiltonian ... $H_S(t)\to H_S(0)$",
            ["G-184"],
            ["G-185"],
            tex_lines=[1906, 1909],
        ),
        R(
            "Eq. (G-185) -> Eq. (G-186)",
            r"source $\mathcal{S}$ after static approximation",
            "algebra",
            "ALGEBRAIC_EQUIVALENCE",
            r"under this assumption, a direct calculation yields",
            ["G-185"],
            ["G-186"],
            tex_lines=[1910, 1915],
        ),
        R(
            "Eq. (G-186) -> Eq. (G-187)",
            r"$\Gamma$ truncation $\mathcal{S}=2i\Gamma\rho_0+O(\Gamma^2)$",
            "asymptotic expansion",
            "ASYMPTOTIC_CLAIM",
            r"by expanding the dissipation parameter around $\Gamma=0$ and strictly retaining only the first-order term",
            ["G-186"],
            ["G-187"],
            parent_status="UNKNOWN_REMAINDER",
            condition=r"author-declared $O(\Gamma^2)$ remainder plus static-Hamiltonian approximation",
            tex_lines=[1917, 1924],
        ),
        R(
            "Eq. (G-187) -> Eq. (G-188)",
            r"Lorentzian as Fourier convolution $e^{-\Gamma|k|}$",
            "special function identity",
            "SPECIAL_FUNCTION_IDENTITY",
            r"these higher-order contributions can be systematically extracted by expressing the integral as a convolution",
            ["G-187"],
            ["G-188"],
            tex_lines=[1925, 1928],
        ),
        R(
            "Eq. (G-187) -> Eq. (G-189)",
            r"RTA/IFR Liouville equation after two approximations",
            "definition",
            "DEFINITION_INSERTION",
            r"applying these two approximations reduces the source term to $\mathcal{S}\simeq 2i\Gamma\rho_0$",
            ["G-187"],
            ["G-189"],
            tex_lines=[1930, 1936],
        ),
    ]


def all_relations() -> list[dict]:
    rels = list(RELATIONS) + extend_d() + extend_e() + extend_f() + extend_g()
    for i, r in enumerate(rels):
        r["internal_id"] = f"R{i+1:03d}"
    return rels


def dump() -> None:
    rels = all_relations()
    # YAML-ish dump without requiring extra deps beyond stdlib for freeze file.
    lines = [
        "schema_version: FlagshipRelationsFrozenV1",
        'paper: "Zhichao Guo et al., Phys. Rev. Lett. 136, 206303 (2026)"',
        'arxiv: "2511.16422v2"',
        "n_relations: {}".format(len(rels)),
        "note: >",
        "  Frozen before verification. Claimed move is independent of engine outcome.",
        "  Printed equation numbers are the public identifiers.",
        "  Unnumbered Key Identities may appear as sources with empty printed list.",
        "relations:",
    ]
    for r in rels:
        lines.append(f"  - internal_id: {r['internal_id']}")
        lines.append(f"    display: {json.dumps(r['display'])}")
        lines.append(f"    cue: {json.dumps(r['cue'])}")
        lines.append(f"    move: {json.dumps(r['move'])}")
        lines.append(f"    claimed: {r['claimed']}")
        lines.append(f"    prose: {json.dumps(r['prose'])}")
        lines.append(f"    sources: {json.dumps(r['sources'])}")
        lines.append(f"    targets: {json.dumps(r['targets'])}")
        lines.append(f"    executable: {str(r['executable']).lower()}")
        lines.append(f"    helper: {str(r['helper']).lower()}")
        if r["parent_status"]:
            lines.append(f"    parent_status: {r['parent_status']}")
        if r["regression"]:
            lines.append(f"    regression: {r['regression']}")
        lines.append(f"    condition: {json.dumps(r['condition'])}")
        if r["subst"]:
            lines.append(f"    subst: {json.dumps(r['subst'])}")
        if r["left"] is not None:
            lines.append(f"    left: {json.dumps(r['left'])}")
        if r["right"] is not None:
            lines.append(f"    right: {json.dumps(r['right'])}")
    (ROOT / "RELATIONS_FROZEN.yaml").write_text("\n".join(lines) + "\n")
    payload = [{k: v for k, v in r.items()} for r in rels]
    (ROOT / "machine_records" / "relations_frozen.json").parent.mkdir(exist_ok=True)
    (ROOT / "machine_records" / "relations_frozen.json").write_text(
        json.dumps({"n": len(payload), "relations": payload}, indent=2) + "\n"
    )
    n_exec = sum(1 for r in rels if r["executable"])
    n_help = sum(1 for r in rels if r["helper"])
    print("relations", len(rels), "executable", n_exec, "helper", n_help)


if __name__ == "__main__":
    dump()
